### ISSUE TITLE
libssl1.0.0 error

### ISSUE THREAD

**Issue by saymoncoppi** [matthewhartman/debian-setup#1]
Hello matthew! Nice guide!
I found an issue when I tried to upgrade the kernel, simple to fix... libssl1.0.0 inst installed by default!

$ wget http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb

$ dpkg -i libssl1.0.0*.deb

$ apt update & upt upgrade

$ uname -r

: )

**Comment by matthewhartman** [comment]
Thanks man! :)

Yes, I came across this issue now that you mention it. I have made the amendments.

Cheers, 

Matt :)
