### ISSUE TITLE
removing old kernel

### ISSUE THREAD

**Issue by saymoncoppi** [matthewhartman/debian-setup#2]
After the new kernel installation maybe  you could suggest how to remove the preview version. What you think? It saves ~200MB of old files.

#check the current kernel version:
$ uname -r 

#check the list of preview installed:
$ dpkg --list | grep linux-image 

#remove the old entry:
$ sudo apt-get purge linux-image-x.x.x-x

#update the bootloader:
$ sudo update-grub2 

:)

**Comment by matthewhartman** [comment]
Good call.

I usually do this, but was a bit reluctant of adding this step in case someone tab completes the wrong kernel and then they will have no kernel to fallback to.

I’ll make it an optional step after updating kernel and reboot (just to make sure there are no broken drivers in the update)

Thanks again for your helpful contributions and I hope you like my setup :)

**Comment by matthewhartman** [comment]
All done now my friend. Thanks again! :)
