### ISSUE TITLE
No installation candidate

### ISSUE THREAD

**Issue by au8st** [matthewhartman/debian-setup#3]
Hi,

Thought I would give this a try, however the following packages are not available in Debian 11:

* [nomacs](https://packages.debian.org/search?keywords=nomacs)
* [obmenu](https://packages.debian.org/search?keywords=obmenu)

I hope that helps

**Comment by au8st** [comment]
I've noticed also `git` is not installed in the required packages, folders have no been generated namely `mkdir ~/.config` , `mkdir ~/.themes` & `sudo mkdir -p /usr/share/slim/themes/`

I've aborted at stage where `slim.conf` does not exist, this is on a headless install.

**Comment by matthewhartman** [comment]
Hey! 

So sorry, I don't know why I didn't get an email about this issue.

Did you manage to sort it out? - Let me know, I can try and help out :)

Cheers
